### ISSUE TITLE
NAS 或者 openwrt 可以配置到么？ 谢谢

### ISSUE THREAD

**Issue by nevertoday** [wibus-wee/raycast-unblock#23]
### Clear and concise description of the problem

这样我就不用每台机器都配置docker了

### Suggested solution

这样我就不用每台机器都配置docker了

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wibus-wee** [comment]
请参照 README 中的 Deploy to remote server 章节

另外，文档中漏写了，你还需要把 config.toml 中的 general.host 改为 0.0.0.0，把 general.mode 改为 remote

**Comment by nevertoday** [comment]
@nevertoday 谢谢。 没有搞定， 换node方案， 也不行。 没有用surge 之类。

**Comment by wibus-wee** [comment]
> @nevertoday 谢谢。 没有搞定， 换node方案， 也不行。 没有用surge 之类。 

那你是使用了什么 mitm 工具？

**Comment by nevertoday** [comment]
我任何mitm工具都没有用

**Comment by nevertoday** [comment]
我现在在nas上弄了部署，但是那个activate.js我找不到修改方案。

**Comment by wibus-wee** [comment]
目前 Raycast Unblock 必须搭配 MitM 工具使用，没有内置 MitM

`activator.js` 是来自 wibus-wee/activation-script 仓库，你需要自行构建才能获得它

> 但是，wibus-wee/activation-script 是依赖 Surge 的脚本功能的

你需要想办法让 Raycast 内的请求能被转接到你的 NAS 上并由 Raycast Unblock 处理，这里可以提供一个关键词：`/etc/hosts` 但是这部分文档中描述不多，你可能需要自行了解（或者🤔 或许以后我也会有这种需求的时候我会更详细写的😂）

**Comment by nevertoday** [comment]
我很头疼.... 我不想用surge 这个大软件~~~ 其次nas 上 我也没有找到文件
hosts 我不是修改指定了么... 就是肝不动
奇怪！

**Comment by nevertoday** [comment]
你的意思是我nas 上其实构建好了，但是我需要一个mitm软件， 劫持这种访问...

**Comment by wibus-wee** [comment]
就是这样的😂
hosts 不要在 nas 上改啊！ 我想着的是你要在使用到电脑上修改hosts把请求转给raycast
但是可能有些其他情况，我也没有去仔细研究过这种
至于 activator 那个是给 Surge 用的😂，和你nas部署啥的没关系

**Comment by nevertoday** [comment]
我nas 地址是 192.168.2.142
macos 上修改了对应的hosts ， 但是还是不行~~~
所以， 我必需得寄出mitm这种
心累

**Comment by wibus-wee** [comment]
大概率你需要一个ssl才能正常请求到

你可以先试试访问 backend.raycast.com 能不能返回数据？感觉大概应该是爆拒绝连接🤔

同时注意一下 raycast unblock 有没有出现什么报错

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/cd85c7e1-4c0b-4a07-a0aa-a0177c12ca67)
访问是我的nas 页面

**Comment by nevertoday** [comment]
nas 我是有ssl的

**Comment by wibus-wee** [comment]
噢...我还忘了...你需要设置general.port为80

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/ab01d3f5-5be3-4daa-a513-63ee956c4dd3)

**Comment by wibus-wee** [comment]
或者🤔通过其他方式能从80端口进去raycast unblock

**Comment by nevertoday** [comment]
我是这样设置的：
[General]
# If you deploy this service on a remote server,
# it is recommended to set mode to "remote", maybe one day this program will be used
# and you **should** set host to "0.0.0.0", or you can't access the service from the outside
mode = "remote"
port = 80
host = "0.0.0.0"
# If there are some problems, you can set debug & logger to true
debug = false
# Fastify Logger
logger = false

**Comment by nevertoday** [comment]
> 或者🤔通过其他方式能从80端口进去raycast unblock

软~~~~xxx路由防火墙~

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/beb99b9f-a098-4d14-8972-ce82aa63be93)
难道不要mitm。。。。就这么难搞么

**Comment by wibus-wee** [comment]
😰之后有时间我看看...抱歉 我现在还真不太清楚怎么搞这个

**Comment by nevertoday** [comment]
{"name":"raycast-unblock","version":"0.2.0-beta.0","author":"wibus-wee <wibus@qq.com>"}

**Comment by wibus-wee** [comment]
> http://backend.raycast.com:3000/
> 
> 这样的访问反而可以：
> 
> http://backend.raycast.com:3000/
> 
> ——————
> 
> 是不是我修改端口逻辑就好了？ 

你怕不是没重启raycast unblock（

大概是这样的

**Comment by nevertoday** [comment]
谢谢， 我重启好多次了。 感觉莫名了， 谢谢了， 您忙您的吧， 我再碰碰运气。

**Comment by nevertoday** [comment]
我在nas上设置了一个反向代理，现在
http://backend.raycast.com/
可以得到内容：
`{"name":"raycast-unblock","version":"0.2.0-beta.0","author":"wibus-wee <wibus@qq.com>"}`
但是raycast 那边还是没有unlock

**Comment by wibus-wee** [comment]
当你激活 raycast 窗口时，raycast unblock会报错误吗？
如果没有的话，尝试重启raycast

**Comment by nevertoday** [comment]
没有报错，但是我多次重启电脑和raycast 还是没有解锁， 也没有任何报错。

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/848c759c-c367-46e4-a4fe-516f58c99dda)
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/d632b5c4-9760-4140-853d-fba33feeb47c)

**Comment by wibus-wee** [comment]
那你把 debug 和 logger 打开，之后激活raycast窗口后把输出的日志发过来一下😂

感谢🥹

**Comment by nevertoday** [comment]
好的。

**Comment by nevertoday** [comment]
[wibuswee-raycast-unblock1.csv](https://github.com/wibus-wee/raycast-unblock/files/14236944/wibuswee-raycast-unblock1.csv)

**Comment by wibus-wee** [comment]
？你没有启动吧🤔 general.debug 和 general.logger 你都设置为 true 了？

**Comment by nevertoday** [comment]
我启动了， 两个地方我都是true

**Comment by nevertoday** [comment]
启动就是启动对应docker ，还是我还有多输入一个命令？

**Comment by wibus-wee** [comment]
那恐怕是程序出问题了...

我一会儿看看为什么...

**Comment by wibus-wee** [comment]
我无法复现你这个设置为true但依旧无法显示日志的问题... 如果成功设置的话，启动的时候会出现类似于这些的信息：

![CleanShot 2024-02-12 at 19 54 04@2x](https://github.com/wibus-wee/raycast-unblock/assets/62133302/9caa5bb0-e487-4538-b110-35d7b2d50457)

**Comment by nevertoday** [comment]
```
Reason: HTTP response received with error
Domain: network
Time: 13:08:04.999
Service: Internal networking engine
Underlying: 
	Domain: NSURLErrorDomain -1200
	Recovery: Would you like to connect to the server anyway?
	_NSURLErrorRelatedURLSessionTaskErrorKey: (
    "LocalDataTask <91678D37-5880-4838-AEFB-313F4458DA4A>.<207>"
)
	_kCFStreamErrorDomainKey: 3
	NSErrorClientCertificateStateKey: 0
	NSLocalizedDescription: An SSL error has occurred and a secure connection to the server cannot be made.
	NSUnderlyingError: 
		Domain: kCFErrorDomainCFNetwork -1200
		_kCFStreamErrorDomainKey: 3
		_kCFNetworkCFStreamSSLErrorOriginalValue: -9802
		kCFStreamPropertySSLPeerCertificates: (
    "<cert(0x112630200) s: www.soname123.com i: TrustAsia RSA DV TLS CA G2>",
    "<cert(0x112735600) s: TrustAsia RSA DV TLS CA G2 i: AAA Certificate Services>"
)
		_kCFStreamErrorCodeKey: -9802
		_kCFStreamPropertySSLClientCertificateState: 0
		kCFStreamPropertySSLPeerTrust: <SecTrustRef: 0x600002deec60>
	NSErrorPeerCertificateChainKey: (
    "<cert(0x112630200) s: www.soname123.com i: TrustAsia RSA DV TLS CA G2>",
    "<cert(0x112735600) s: TrustAsia RSA DV TLS CA G2 i: AAA Certificate Services>"
)
	_kCFStreamErrorCodeKey: -9802
	_NSURLErrorFailingURLSessionTaskErrorKey: LocalDataTask <91678D37-5880-4838-AEFB-313F4458DA4A>.<207>
	NSURLErrorFailingURLPeerTrustErrorKey: <SecTrustRef: 0x600002deec60>
	NSErrorFailingURLStringKey: https://backend.raycast.com/api/v1/store_listings?include_native=true&per_page=25&page=1
	NSErrorFailingURLKey: https://backend.raycast.com/api/v1/store_listings?include_native=true&per_page=25&page=1
```

**Comment by nevertoday** [comment]
你的是local ，我的是remote ，这个不同吧

**Comment by nevertoday** [comment]
我反复检查了， 我几个地方都是true：
```
    1 [General]
    2 # If you deploy this service on a remote server,
    3 # it is recommended to set mode to "remote", maybe one day this program will be used
    4 # and you **should** set host to "0.0.0.0", or you can't access the service from the outside
    5 mode = "remote"
    6 port = 80
    7 host = "0.0.0.0"
    8 # If there are some problems, you can set debug & logger to true
    9 debug = true
   10 # Fastify Logger
   11 logger = true
```

**Comment by nevertoday** [comment]
找到日志了
我确实服务器上 的true 没有成功， 刚刚我修改好了
[wibuswee-raycast-unblock1.csv](https://github.com/wibus-wee/raycast-unblock/files/14238733/wibuswee-raycast-unblock1.csv)

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/ed2194f7-f9d7-493c-a28c-37b08f9e9d04)

**Comment by wibus-wee** [comment]
你别把包含了你的key的日志发上来😂

你还需要激活一次 Raycast 窗口来出发请求，比如这样：


https://github.com/wibus-wee/raycast-unblock/assets/62133302/2636fe3b-787a-4a92-bb3b-cf9678c79538

接着，把显示出来的日志发过来看看 **（别把含有你的 key 的日志发上来！）**

**Comment by wibus-wee** [comment]
> 你的是local ，我的是remote ，这个不同吧

目前暂时 Raycast Unblock 对这两种模式没有做区分处理，但是以后改进使用体验的过程里一定会用到的

**Comment by nevertoday** [comment]
激活窗口， 日志也不会变化

**Comment by nevertoday** [comment]
日志还是如上这些， 没有任何异常的

**Comment by wibus-wee** [comment]
你的程序部署有问题，正常情况下一旦 Raycast 发出请求并且 Raycast Unblock 托管了这个请求它会输出一堆日志的，包括且不限于处理逻辑和fastify log

如果没有变化，那就是你没有成功将请求交由 Raycast Unblock 托管

**Comment by nevertoday** [comment]
继续蹲nas 方案。

**Comment by Ssttar** [comment]
![CleanShot 2024-03-03 at 17 06 41](https://github.com/wibus-wee/raycast-unblock/assets/104423295/9798bd2a-c4b1-4571-b18a-d6429b6c832e)
![CleanShot 2024-03-03 at 17 09 59](https://github.com/wibus-wee/raycast-unblock/assets/104423295/76627397-340a-422e-b940-76b5c5928728)

![CleanShot 2024-03-03 at 16 55 02](https://github.com/wibus-wee/raycast-unblock/assets/104423295/05167bd6-e9bd-4dad-b685-77f25a8caf09)
![CleanShot 2024-03-03 at 17 11 24](https://github.com/wibus-wee/raycast-unblock/assets/104423295/08dfc53f-55d2-4e1b-a94b-47bdae5a8142)
![CleanShot 2024-03-03 at 17 11 32](https://github.com/wibus-wee/raycast-unblock/assets/104423295/c5259f4a-9923-4782-ac63-383d0e22f65b)

![CleanShot 2024-03-03 at 16 53 32](https://github.com/wibus-wee/raycast-unblock/assets/104423295/2746b81a-bad9-49bf-bf57-073d27b82029)
没什么问题，群晖nas部署的，使用surge

**Comment by Ssttar** [comment]
> 继续蹲nas 方案。

你需要一个mitm工具

**Comment by nevertoday** [comment]
我不希望安装surge之类的工具~~~ 任何这种mitm工具，尤其是复杂的

**Comment by wibus-wee** [comment]
我已经验证过了，同样的docker部署方式，并没有出现任何问题

我认为项目实现上是没有问题的

**Comment by nevertoday** [comment]
@wibus-wee 你怎样搞定的哦， 你么有用到surge 之类的工具？

**Comment by wibus-wee** [comment]
rewrite header.

我思索了一下关于你的问题，后面我会新开一个 feature issue 来尽可能地解决它.

**Comment by nevertoday** [comment]
就能不用surge么， 那么一个软件，不是和我软路由冲突了么

**Comment by wibus-wee** [comment]
> 就能不用surge么， 那么一个软件，不是和我软路由冲突了么

我认为是的

这个方案大概率应该可以实现部署在内网nas下通过修改hosts来篡改请求的功能吧

或者你使用别的，任意的，可以rewrite request header 的方案即可，不过rewrite raycast客户端的就好，不要重写raycast unblock的

surge只是一个稍微常见一点的、我在用的工具罢了

**Comment by wibus-wee** [comment]
> 就能不用surge么， 那么一个软件，不是和我软路由冲突了么

我已经提出了 PR：https://github.com/wibus-wee/raycast-unblock/pull/42

同时在 PR 分支更新了文档，你可以使用此 PR 内的代码 + 文档来尝试一下能否支持使用了

文档：https://github.com/wibus-wee/raycast-unblock/tree/feat/https-support?tab=readme-ov-file#generate-self-signed-certificate-to-use-with-raycast-unblock

**Comment by nevertoday** [comment]
请教：
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/00d068bb-6ea3-4b37-8e90-947cf91a8284)

为什么这种报错

**Comment by nevertoday** [comment]
This is an advanced operation and it may require some technical skills. It is only suitable for production deployment in a remote server.

Open your config file, set enabled to true in [General.Https], fill in your host's local IP in host, and leave others as default.
Then start Raycast Unblock, it will automatically setup HTTPS for the service and install the CA certificate.
Go to the CA Root certificate storage (it will be shown in Raycast Unblock's log), export two files in it ( rootCA-key.pem, rootCA.pem ), and save these two files to /Users/<YOUR USERNAME>/Library/Application Support/mkcert (create it if not exists) in the computer that runs Raycast.
Go to [FiloSottile/mkcert Release](https://github.com/FiloSottile/mkcert/releases/tag/v1.4.4), download and use the executable file that matches your Raycast computer's architecture, and rename it to mkcert.
Then run the following command after replacing the placeholders in the command:
./mkcert -install
When it shows The local CA is now installed in the system trust store! ⚡️, it means the installation is successful. You can use Raycast Unblock by specifying hosts now!

____
这个部分的证书没有在日志中，奇怪。

**Comment by nevertoday** [comment]
Open your config file, set enabled to true in [General.Https], fill in your host's local IP in host, and leave others as default.

配置文件中也没有找到https 这个开启true的地方

**Comment by nevertoday** [comment]
toml文件我这样写的：
[General]
# If you deploy this service on a remote server,
# it is recommended to set mode to "remote", maybe one day this program will be used
# and you **should** set host to "0.0.0.0", or you can't access the service from the outside
mode = "remote"
port = 3000
host = "0.0.0.0"
# If there are some problems, you can set debug & logger to true
debug = true
# Fastify Logger
logger = false
# If you want the service to listen to the changes of the configuration file and update automatically,
# you can set watch to true
watch = false

**Comment by wibus-wee** [comment]
你看一下最新的 config.example.toml，我更新了，li m you de

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/d183a4f7-d3f7-41bf-a543-df99b62c1e3b)

真的没有看到

**Comment by wibus-wee** [comment]
看 feat/https-support 分支的代码...

<img width="269" alt="CleanShot 2024-04-04 at 21 49 43@2x" src="https://github.com/wibus-wee/raycast-unblock/assets/62133302/d822c645-7e37-4f40-b058-44cf08e3d6d5">

```conf
[General.Https]
# If you want to use HTTPS, you can set the following configuration
enabled = true
## You can specify the host to the certificate file (auto generate mode)
host = '192.168.3.2'
## You can also specify the path to your existing certificate file
# key = "path
# cert = "path"
# ca = "path"
```

**Comment by wibus-wee** [comment]
不对... 你不会是在用 docker 来尝试使用这个功能吧？？

呃呃算了，我先合并发版吧. 我测试过是没有问题的了

**Comment by nevertoday** [comment]
我是在nas上的docker 中使用...

**Comment by nevertoday** [comment]
好。 我看到toml文件中，还是之前版本的内容，奇怪。

**Comment by nevertoday** [comment]
我找找分支

**Comment by nevertoday** [comment]
feat/https-support  这个我没有找到分支...

**Comment by nevertoday** [comment]
幕友找到~    😭

**Comment by wibus-wee** [comment]
咳咳咳 我有点开始急了（（

不在那里了已经😭 已经合并到main了😭 你去看下主分支的example吧😭

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/bc1e0c26-4bdd-491a-9c3e-44a2dd875264)

![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/0e4113b4-985d-442b-aedd-ef4bf0a148a0)

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/9fea9534-ef3d-404a-889b-a82e87a3237b)

**Comment by nevertoday** [comment]
[General]
# If you deploy this service on a remote server,
# it is recommended to set mode to "remote", maybe one day this program will be used
# and you **should** set host to "0.0.0.0", or you can't access the service from the outside
mode = "local"
port = 443
host = "0.0.0.0"
# If there are some problems, you can set debug & logger to true
debug = true

**Comment by nevertoday** [comment]
这种地方是local 么？

**Comment by wibus-wee** [comment]
设置成remote吧（虽然现阶段这俩没啥区别）

port 要 443.

之后按照文档走吧

**Comment by nevertoday** [comment]
后续是从nas 上拷贝证书下来到本机，但是，我的对应目录下没有证书，奇怪

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/e743feea-ec8b-4700-8f35-cd7be2046393)

**Comment by nevertoday** [comment]
Go to the CA Root certificate storage (it will be shown in Raycast Unblock's log), export two files in it ( rootCA-key.pem, rootCA.pem ),

————————
这两个东西好难翻到

**Comment by wibus-wee** [comment]
Raycast Unblock 没有显示 CA Root certificate 储存位置的日志吗？

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/0c7cb0a6-09d4-40be-a564-ee7ea23a3724)
![iShot_2024-04-04_23 05 48](https://github.com/wibus-wee/raycast-unblock/assets/166048/a7f37f98-39ba-454b-84e5-87496dbed4e6)
![iShot_2024-04-04_23 05 29](https://github.com/wibus-wee/raycast-unblock/assets/166048/22c77817-5fdf-499c-861a-38157d67972f)

——————
但是死活都没有这个文件

**Comment by nevertoday** [comment]
这个目录都不回有的~ share
 这个目录都没有。

**Comment by wibus-wee** [comment]
为什么你这个 docker terminal 的 root 里这么多奇怪的文件的？

**Comment by wibus-wee** [comment]
他是储存在你的docker容器里的

你得去docker容器里找

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/fb527870-4e8d-465e-98e4-fac588b9870a)

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/860a326c-f05c-414f-83c1-fd86b410aca9)
我直接打包下载后发现有这个，是不是就是这两个东西？

**Comment by wibus-wee** [comment]
是的是的

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/0a53c227-40d9-4f8a-a208-1e67e972525f)

搞笑了， 最后执行命令，直接报错惹

**Comment by wibus-wee** [comment]
这个是mkcert的问题了... 你需要去看看mkcert有没有相关issue了

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/3e8ae593-b5cd-46f3-a9ba-20a00646e23d)
必需是这个目录中的文件
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/337a5aaf-f9e3-48c6-bf4d-d09bd6b2bf51)

**Comment by nevertoday** [comment]
这个命令成功了， 但是还没有成功解锁

**Comment by nevertoday** [comment]
我hosts 需要修改么？

**Comment by wibus-wee** [comment]
肯定要改啊

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/f6211467-970c-4d25-8917-4b48fb2c956e)

hosts修改了，还是没有动静

**Comment by wibus-wee** [comment]
重启 raycast，看看 docker 那边有没有出现请求日志记录

**Comment by wibus-wee** [comment]
> ![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/e743feea-ec8b-4700-8f35-cd7be2046393)
> 
> 

3000？ 你这样不会导致没法直接80/443访问的吗

**Comment by nevertoday** [comment]
我要怎样设置？

**Comment by nevertoday** [comment]
我的nas 后台访问不是这个端口

**Comment by nevertoday** [comment]
日志中并没有出现请求

**Comment by wibus-wee** [comment]
需要 backend.raycast.com 直接就能访问的，而不是还要加什么 backend.raycast.com:3000 这样的端口好

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/bc8f1b37-c13d-4550-b3da-7ddd0a67dfd0)

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/92611f88-a9d7-4509-acfd-e38df097734c)

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/acb008ff-649e-4ca4-ab0f-526d8da7c2b7)

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/1d9c6159-41e6-49b2-9b22-7c42a0228511)

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/c84a97c0-564d-43b5-838f-0b10d6318ee8)

**Comment by wibus-wee** [comment]
🥹 剩下的我不知道了

我只能知道 如果实现了的话 是可以做到修改hosts来篡改 raycast 数据的

因为我已经测试过了. 虽然我没有 NAS，但是我目前将其部署在一台不使用 raycast 的 MacBook 中，并将 443 弄了出去，接着在别的机器上指定 host 完成了篡改

我对这方面的了解非常少，所以我也很难去帮助您🥹 我尽我所能做了最后的我能做工作了

**Comment by nevertoday** [comment]
谢谢你， 我也是倔强， 自己也不懂这些
纯粹是为了刚而刚
明明自己都有两个plus 还折腾这些

**Comment by nevertoday** [comment]
我现在放出了443 但是 ... https 不行。

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/3b2dc624-89de-4169-bad0-c1d55a9c6796)

**Comment by wibus-wee** [comment]
无论如何，无论是做什么

目的只有一个，就是可以通过 https://backend.raycast.com 访问到 raycast unblock

不带端口号，包含 https 协议

只要做到这个，无论是什么办法都可以了😌

**Comment by wibus-wee** [comment]
🤔啊？你的安装ca证书是从docker容器里下载的吗？ 看看你的macOS里的“钥匙串访问”

里面找一下mkcert开头的证书看看有没有？

**Comment by wibus-wee** [comment]
还是你反向代理什么的又换了一层证书？

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/033dd887-7fc0-44c4-8fb4-b93bfe599d4f)

**Comment by nevertoday** [comment]
我重新做证书吧

**Comment by nevertoday** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/166048/46f82e73-eeea-4fff-8b49-844b12d84ee7)

**Comment by nevertoday** [comment]
原地放弃，坐等后面的牛人， 有缘share

**Comment by wibus-wee** [comment]
哎...现在的问题就不是我的服务端的问题了我觉得🥲

**Comment by nevertoday** [comment]
难搞。 谢谢了

**Comment by aerosonic-jp** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Aengelus, @wtzb, @narisada014, @WiseChannel, @technologyinvestor, @mhz987, @geoffwellman, @richardjypark, @liuderchi, @6boris, @iAMNABHON, @luis-herasme, @dozortsev, @gokhansa, @itskhanow, @johnexzy, @leodsoft, @chenbimo, @pkuhonker, @hhh2012aa, @mvpotter, @intellectb, @aurda012, @voith, @jasoncui, @TicTacWeb3, @2pai, @DouglasPimentel, @zsxueyuan, @PoliZyh, @kangshuisheng, @Harnek, @WillianLiusHao, @Kabie, @minyangcheng, @pi-ka, @nekofar, @frkcn, @bankel, @0rhan, @linkinzhiyuan, @ziyacan, @shengzhc, @criticalbh, @xxlv, @zhanba, @Shouperman, @Hokid, @blipn, @xianshuiAceysx, @wantzjt-zz, @yorusiku, @MehranMazhar, @shawnmoyer, @okwme, @neryajanel, @xitong-0629, @drkchain, @TheRealFREDP3D, @nelreina, @tranhan66, @goldcatglass, @joyceczy, @kyuiki, @julianclatro, @linfui, @thomasschulze, @Lengso, @viczhangge, @KhanUbel, @html-krit, @alpha0-dev, @jmmanos, @haimenlinchen, @ro2lfish, @lubarskyy, @eliseumds, @luo9527k, @anhgeeky, @shahradelahi, @h0ngcha0, @eizyc66, @zbndm, @huruji, @mtxmzkqlhc, @varinliali, @mster, @ouxch, @silviu-dima, @jeremyfn, @yofine, @adamrhunter, @escottalexander, @gabrielAnzaldo, @memorylane80, @jarvisaoieong, @zhouzhuhao, @t83714, @woheV6

**Comment by nevertoday** [comment]
最近是不是更新了nas 的方案？

**Comment by wibus-wee** [comment]
@tianzhuwei 这应该是个 bug，你重开个 issue 吧

**Comment by tianzhuwei** [comment]
> @tianzhuwei 这应该是个 bug，你重开个 issue 吧

ok 我开个

**Comment by wibus-wee** [comment]
由于这个 issue 已经太长了，如果后续有其他问题的话，大家就再创建一个新issue吧，感谢
