### ISSUE TITLE
按文档配置，解锁未生效

### ISSUE THREAD

**Issue by AmintaCCCP** [wibus-wee/raycast-unblock#71]
### Describe the bug

使用的本地docker服务，利用surge MITM后台地址，重写header到本地docker服务。
1. 本地服务检查没问题：
<img width="388" alt="image" src="https://github.com/wibus-wee/raycast-unblock/assets/74942183/3a49df8f-b7d1-412e-973f-8490dfc6b78c">

2. surge重写正常
<img width="1446" alt="image" src="https://github.com/wibus-wee/raycast-unblock/assets/74942183/f5b8df4d-676c-459e-8d25-6d7c83b374b6">

3. raycast解锁不生效
<img width="1000" alt="image" src="https://github.com/wibus-wee/raycast-unblock/assets/74942183/7d241950-4391-4235-9a65-5ea18db7c95e">
尝试重启raycast，重新安装均不行。

### Reproduction

按照文档配置，解锁未生效

### System Info

```Shell
环境：
MacOS 14.5 Beta (23F5064f)
Raycast 1.72.1
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wibus-wee** [comment]
能启动raycast unblock的debug模式，重启
截图在激活raycast时请求me接口的时候的日志吗

**Comment by AmintaCCCP** [comment]
> 能启动raycast unblock的debug模式，重启 截图在激活raycast时请求me接口的时候的日志吗
好像body里没东西
![image](https://github.com/wibus-wee/raycast-unblock/assets/74942183/a9e5ed20-2fd4-4ce1-97ad-459bfc404f20)

**Comment by AmintaCCCP** [comment]
用surge抓了一下，的确请求时候body是空的
<img width="966" alt="image" src="https://github.com/wibus-wee/raycast-unblock/assets/74942183/dcce4da2-350e-4397-87be-a6d989bc21ec">
<img width="1891" alt="image" src="https://github.com/wibus-wee/raycast-unblock/assets/74942183/47f5cc2c-5de1-4c58-bd3f-346274317916">

**Comment by wibus-wee** [comment]
你的unblock有走surge代理吗？

**Comment by AmintaCCCP** [comment]
> 你的unblock有走surge代理吗？

抓包看走的是direct规则，而且docker那个假后台有返回500，走代理的话应该接收不到response

**Comment by AmintaCCCP** [comment]
找到问题了，解密失败。
<img width="1446" alt="image" src="https://github.com/wibus-wee/raycast-unblock/assets/74942183/14ebfd9e-8933-4fbd-b8a2-7ab3b2b73270">

**Comment by wibus-wee** [comment]
要不别让它受surge接管？我这好像没遇到这问题诶

**Comment by AmintaCCCP** [comment]
> 要不别让它受surge接管？我这好像没遇到这问题诶

我看文档里说要让surge重写header，不接管的话没法重写啊

**Comment by wibus-wee** [comment]
我是说你别让surge接管unblock

我目前是新版

**Comment by wibus-wee** [comment]
可能我要花点时间看看这是什么情况...

先前在整别的的时候遇到过，但是我忘记是什么导致的了😂

**Comment by AmintaCCCP** [comment]
> 我是说你别让surge接管unblock
> 
> 我目前是新版
试了全局direct和排除docker进程还是不行。
我也再想想看有没有别的招，起码知道大概是什么问题了。要是有幸搞好了我再分享下避坑攻略。
十分感谢大佬的帮助~

**Comment by wibus-wee** [comment]
我晚点看看什么问题吧

**Comment by wibus-wee** [comment]
🥺我这里复现不了不知道为什么

**Comment by AmintaCCCP** [comment]
估计是surge里的某些奇奇怪怪的配置

**Comment by bxb100** [comment]
1. 需要先设置 Https 解密 MitM 主机名 `backend.raycast.com`
2. URL 重写 Header `https:\/\/backend.raycast.com` 到你的域名

**Comment by imoyy** [comment]
启用增强模式接管orbstack这个软件后会导致无法解密，仅使用Surge的系统代理并将orbstack的"proxy"修改为"None"可以正常使用。
> [!warning]
> 不会用Surge，Surge可以既开tun模式，又能排除特定软件的方法吗？

**Comment by AmintaCCCP** [comment]
> 启用增强模式接管orbstack这个软件后会导致无法解密，仅使用Surge的系统代理并将orbstack的"proxy"修改为"None"可以正常使用。
> 
> Warning
> 
> 不会用Surge，Surge可以既开tun模式，又能排除特定软件的方法吗？

感谢，的确是orbstack设置的问题

**Comment by CNSCSQ** [comment]
> > 启用增强模式接管orbstack这个软件后会导致无法解密，仅使用Surge的系统代理并将orbstack的"proxy"修改为"None"可以正常使用。
> > Warning
> > 不会用Surge，Surge可以既开tun模式，又能排除特定软件的方法吗？
> 
> 感谢，的确是orbstack设置的问题

请问一下，我遇到了同样的问题，最后你是怎么解决的？

**Comment by AmintaCCCP** [comment]
> > > 启用增强模式接管orbstack这个软件后会导致无法解密，仅使用Surge的系统代理并将orbstack的"proxy"修改为"None"可以正常使用。
> > > Warning
> > > 不会用Surge，Surge可以既开tun模式，又能排除特定软件的方法吗？
> > 
> > 
> > 感谢，的确是orbstack设置的问题
> 
> 请问一下，我遇到了同样的问题，最后你是怎么解决的？

就是像楼上说的，把surge的增强模式关了。因为我用的是orbstack，里面有个设置可以不走代理。如果用官方的docker客户端可以找找类似的设置，我记得配置文件里可以改。
