### ISSUE TITLE
Ubuntu22/24 app版本运行出错

### ISSUE THREAD

**Issue by tianzhuwei** [wibus-wee/raycast-unblock#83]
### Describe the bug

根据[wiki](https://wibus-wee.github.io/raycast-unblock/guide/getting-started.html#%F0%9F%8E%89-congratulations)下载ubuntu的打包版本运行出错
下载位置：https://github.com/wibus-wee/raycast-unblock/actions/runs/9047798062
具体情况如图
<img width="719" alt="image" src="https://github.com/wibus-wee/raycast-unblock/assets/16696364/7859a8ca-95a2-44fd-b3fa-9a3a201f9e48">

### Reproduction

ubuntu

### System Info

```Shell
System:
    OS: Linux 6.8 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
    CPU: (1) x64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
    Memory: 308.57 MB / 957.45 MB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 18.19.1 - /usr/bin/node
    npm: 9.2.0 - /usr/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wibus-wee** [comment]
如果可以的话，暂时先用 Docker 版本吧。你这不说我还真没注意 CI 里的 app 到底能不能跑😂

**Comment by tianzhuwei** [comment]
> 如果可以的话，暂时先用 Docker 版本吧。你这不说我还真没注意 CI 里的 app 到底能不能跑😂

macOS 的那个版本没有问题，就是 Ubuntu 这个不行，感觉自动编译的这个有点问题

**Comment by wibus-wee** [comment]
@tianzhuwei 看一下这个打包的：https://github.com/wibus-wee/raycast-unblock/actions/runs/9052447696

应该可以了
