### ISSUE TITLE
Can't Get Pro Features Enabled on M1 Mac

### ISSUE THREAD

**Issue by andrewcincotta** [wibus-wee/raycast-unblock#91]
### Describe the bug

I am on the current version of Raycast and raycast-unblocked, using macOS with an M1 Pro chip. I decided to use the prebuilt bundle and mitmproxy. In a folder I have config.toml, mitm.py, and raycast-unblock-app. Upon running raycast-unblock-app it claims to be on version 0.5.0-beta.1 and listening on  http://0.0.0.0:3000. In another terminal window, I have mitm.py running (shows "Flows" with a mostly empty terminal window). I tried restarting Raycast, but doing the above doesn't seem to change the functionality of my app at all.

### Reproduction

macOS

### System Info

```Shell
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 727.45 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.2.0 - /opt/homebrew/bin/node
    npm: 10.7.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 123.0.6312.107
    Safari: 17.4.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wibus-wee** [comment]
Are you sure mitmproxy successfully redirected the raycast request to raycast unblock?

**Comment by andrewcincotta** [comment]
> Are you sure mitmproxy successfully redirected the raycast request to raycast unblock?

Could it be that the python script contains 'http://127.0.0.1:3000' and the raycast-unblock-app routes to 'http://0.0.0.0:3000'? Other than that, everything was taken directly from the setup guide. I copied the mitm.py and downloaded [this script](https://github.com/wibus-wee/raycast-unblock/actions/runs/9144716073) for my M1 Pro MacBook. On the link given, I downloaded and utilized [raycast-unblock-macos-latest-arm-app](https://github.com/wibus-wee/raycast-unblock/actions/runs/9144716073/artifacts/1516490183)

**Comment by wibus-wee** [comment]
I don't think that's the issue here.

You can start the debug mode of raycast-unblock, restart raycast unblock, activate the raycast window to make a request, and then check whether there are logs in raycast-unblock about receiving the request.

**Comment by andrewcincotta** [comment]
Figured it out. I needed to set up mitmproxy properly.
